version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app
    links:
      - mariadb:mariadb
    env_file:
      - .docker.env
  mariadb:
    image: mariadb:10.4
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=dockerphp
      - MYSQL_ROOT_PASSWORD=password
